### PR TITLE
pure magic and a bucket

### PR DESCRIPTION
**Pull request by Szybet**
[bucket.webm](https://github.com/Kobo-InkBox/gui-bundle/assets/53944559/8c3195ce-2bde-4436-9ecb-68d99f0c8f2c)

please accept this commit i'm reverse enginering the script to make it work for the third time im going insane

### CODE REVIEW

**Comment by tux-linux** [comment]
what broke?

**Comment by Szybet** [comment]
My mind and will to live

Just automate it this repo :(

**Comment by tux-linux** [comment]
what broke in the repo

**Comment by Szybet** [comment]
my hope to humanity

Nothing, i just want this automation script to be in place

**Pull request merged**
